import { Component } from '@angular/core';

@Component({
  template: ''
})
export class BaseComponent {

  public autoGeneratedId = `id_${new Date().getTime().toString()}_${Math.random()}`;

  public clearSting(text: string): string {
    return text.toLowerCase()
      .replace(/[áàãâ]/g, 'a')
      .replace(/[éèê]/g, 'e')
      .replace(/[íìî]/g, 'i')
      .replace(/[óòõô]/g, 'o')
      .replace(/[úùû]/g, 'u')
      .replace(/[ç]/g, 'c')
      .replace(/[\s]/g, '-')
      .replace(/[^a-z0-9]/g, '');
  }

  public generateId(name: string): string {
    if (!name || name === '') {
      return this.autoGeneratedId;
    }

    let words = name.split(' ');

    words = words.map((item, index) => {
      if (index === 0) {
        return this.clearSting(item);
      }

      const clearedString = this.clearSting(item);

      return clearedString[0].toUpperCase() + clearedString.substr(1, clearedString.length);
    });

    return words.join('');
  }
}
